### ISSUE TITLE
Split Open edX parts of this repo out from 2U-specific parts

### ISSUE THREAD

**Issue by kdmccormick** [openedx-unsupported/tubular#614]
## Background

This repo historically has been an assortment of pipeline-related (that is, "tubular" :) Python scripts authored mostly/entirely by edx.org operators. 

The repository is mostly 2U-specific, but there are some parts that are important to the community.

### Parts that we know are relevant to Open edX

(Update this list as we find more)

* ~The modulestore pruner (in https://github.com/openedx/tubular/blob/master/tubular/splitmongo.py).~
  * Update: this no longer works, due the fact that Split now stores active_versions in Django models as part of https://github.com/openedx/platform-roadmap/issues/3. 
* The user retirement pipeline
  * Several files in the "scripts" folder (some of which may be 2U specific)
  * tubular/edx_api.py 
  * tubular/salesforce_api.py (may be 2U specific)

### Urgency

At time of writing, it would be architecturally nice to sort this out, but there is no immediate need to do so. If maintenance of tubular ever becomes an issue, then we'll want to take a look at extracting the parts important to Open edX.

## Tasks

- [ ] Audit the repo: Build final list of parts that are relevant to Open edX.
- [ ] Separate the Open edX parts from the 2U-specific parts.
  - open question: How should we separate them? Move the Open edX stuff, move the 2U stuff, or both? New repo(s) or existing? 
- [ ] Transfer the 2U-specific stuff from the openedx GitHub org back to the edx GitHub org.

**Comment by kdmccormick** [comment]
This is basically a dupe of https://github.com/openedx/public-engineering/issues/244
